#!/bin/bash


set -e

# config.json から入力・出力を読み込む
t1=$(jq -r .t1 /input/config.json)
txt="/raw/header.txt"
# in local
#t1=$(jq -r .t1 /input/config.json)
#txt=$(jq -r .header /input/config.json)


echo "Input T1: $t1"
echo "Output: $txt"

# Run the processing
python main.py "$t1" "$txt"


