#!/bin/bash


set -e

# config.json から入力・出力を読み込む
t1=$(jq -r .t1 config.json)
#t1=$(jq -r .t1 /input/config.json)
txt="/output/header/header.txt"

echo "Input T1: $t1"
echo "Output: $txt"

# Run the processing
python main.py "$t1" "$txt"


